#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    /var/lib/jellyfin/{.ssh,ssh_host_keys,logs/openssh}

USER_NAME=${USER_NAME:-jellyfin}
echo "User name is set to $USER_NAME"

# symlink out ssh config directory
if [ ! -L /etc/ssh ];then
    if [ ! -f /var/lib/jellyfin/ssh_host_keys/sshd_config ]; then
        sed -i '/#PidFile/c\PidFile \/var/lib/jellyfin\/sshd.pid' /etc/ssh/sshd_config
        cp -a /etc/ssh/sshd_config /var/lib/jellyfin/ssh_host_keys/
    fi
    rm -Rf /etc/ssh
    ln -s /var/lib/jellyfin/ssh_host_keys /etc/ssh
    ssh-keygen -A
fi

# set umask for sftp
UMASK=${UMASK:-022}
sed -i "s|/usr/lib/ssh/sftp-server$|/usr/lib/ssh/sftp-server -u ${UMASK}|g" /etc/ssh/sshd_config

# set key auth in file
if [ ! -f /var/lib/jellyfin/.ssh/authorized_keys ];then
    touch /var/lib/jellyfin/.ssh/authorized_keys
fi

[[ -n "$PUBLIC_KEY" ]] && \
    [[ ! $(grep "$PUBLIC_KEY" /var/lib/jellyfin/.ssh/authorized_keys) ]] && \
    echo "$PUBLIC_KEY" >> /var/lib/jellyfin/.ssh/authorized_keys && \
    echo "Public key from env variable added"

[[ -n "$PUBLIC_KEY_URL" ]] && \
    PUBLIC_KEY_DOWNLOADED=$(curl -s $PUBLIC_KEY_URL) && \
    [[ ! $(grep "$PUBLIC_KEY_DOWNLOADED" /var/lib/jellyfin/.ssh/authorized_keys) ]] && \
    echo "$PUBLIC_KEY_DOWNLOADED" >> /var/lib/jellyfin/.ssh/authorized_keys && \
    echo "Public key downloaded from '$PUBLIC_KEY_URL' added"   

[[ -n "$PUBLIC_KEY_FILE" ]] && [[ -f "$PUBLIC_KEY_FILE" ]] && \
    PUBLIC_KEY2=$(cat "$PUBLIC_KEY_FILE") && \
    [[ ! $(grep "$PUBLIC_KEY2" /var/lib/jellyfin/.ssh/authorized_keys) ]] && \
    echo "$PUBLIC_KEY2" >> /var/lib/jellyfin/.ssh/authorized_keys && \
    echo "Public key from file added"

if [ -d "$PUBLIC_KEY_DIR" ];then
    for F in "${PUBLIC_KEY_DIR}"/*;do
        PUBLIC_KEYN=$(cat "$F") && \
        [[ ! $(grep "$PUBLIC_KEYN" /var/lib/jellyfin/.ssh/authorized_keys) ]] && \
        echo "$PUBLIC_KEYN" >> /var/lib/jellyfin/.ssh/authorized_keys && \
        echo "Public key from file '$F' added"
    done
fi

# back up old log files processed by logrotate
[[ -f /var/lib/jellyfin/logs/openssh/openssh.log ]] && \
    mv /var/lib/jellyfin/logs/openssh /var/lib/jellyfin/logs/openssh.old.logs && \
    mkdir -p /var/lib/jellyfin/logs/openssh

# add log file info
[[ ! -f /var/lib/jellyfin/logs/loginfo.txt ]] && \
    echo "The current log file is named \"current\". The rotated log files are gzipped, named with a TAI64N timestamp and a \".s\" extension" > /var/lib/jellyfin/logs/loginfo.txt

# permissions
chown -R "${USER_NAME}":"${USER_NAME}" \
    /var/lib/jellyfin
chmod go-w \
    /var/lib/jellyfin
chmod 700 \
    /var/lib/jellyfin/.ssh
chmod 600 \
    /var/lib/jellyfin/.ssh/authorized_keys